
# Based on example from Angular app deployment with AWS S3, Code Pipeline and Cloud Front
# by Shylesh Giri, url: https://medium.com/@giritech7/angular-app-deployment-with-aws-s3-code-pipeline-and-cloud-front-1011f00e8f59
version: 0.2


env:
  variables:
    BUILD_FOLDER: "dist"

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - npm install
      - npm install -g @angular/cli

  build:
    commands:
      - ng build
artifacts:
  files:
    - "**/*"
  base-directory:
    - 'dist/social-media-angular'